#!/usr/bin/env python3

import random
"""This program plays a game of Rock, Paper, Scissors between two Players,
and reports both Player's scores each round."""

moves = ['rock', 'paper', 'scissors']

"""The Player class is the parent class for all of the Players
in this game"""


class Player:
    def move(self):
        return 'rock'

    def learn(self, my_move, their_move):
        pass


class RandomPlayer(Player):
    def move(self):
        return random.choice(moves)

    def learn(self, my_move, their_move):
        pass


class HumanPlayer(Player):
    def move(self):
        while True:
            move = input("rock, paper, scissors? > ").lower()
            if move in moves:
                return move
            else:
                print("Invalid input, try again")

    def learn(self, my_move, their_move):
        pass


class ReflectPlayer (Player):
    def __init__(self):
        self.their_move = random.choice(moves)

    def move(self):
        return self.their_move

    def learn(self, my_move, their_move):
        self.their_move = their_move


class CyclePlayer (Player):
    def __init__(self):
        self.my_move = random.choice(moves)

    def move(self):
        if self.my_move == "rock":
            return "paper"
        elif self.my_move == "paper":
            return "scissors"
        else:
            return "rock"

    def learn(self, my_move, their_move):
        self.my_move = my_move


def beats(one, two):
    return ((one == 'rock' and two == 'scissors') or
            (one == 'scissors' and two == 'paper') or
            (one == 'paper' and two == 'rock'))


class Game:
    def __init__(self, p1, p2):
        self.p1 = p1
        self.p2 = p2
        self.player_score_1 = 0
        self.player_score_2 = 0

    def play_round(self):
        move1 = self.p1.move()
        move2 = self.p2.move()
        print(f"Player 1: {move1}  Player 2: {move2}")
        if beats(move1, move2):
            print("Player1 wins")
            self.player_score_1 += 1
        elif beats(move2, move1):
            print ("Player2 wins")
            self.player_score_2 += 1
        else:
            print ("Tie")
        self.p1.learn(move1, move2)
        self.p2.learn(move2, move1)

    def play_game(self):
        print("Game start!")
        for round in range(3):
            print(f"Round {round}:")
            self.play_round()
        print("Game over!")
        print(f"Player1:{self.player_score_1} Player2: {self.player_score_2}")
        if self.player_score_1 > self.player_score_2:
            print ("Player1 wins the game")
        elif self.player_score_2 > self.player_score_1:
            print ("Player2 wins the game")
        else:
            print ("this game is a tie")

if __name__ == '__main__':
    game = Game(HumanPlayer(), RandomPlayer())
    game.play_game()
